[package]
name = "fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
rusqlite = {workspace = true, features = ["blob", "url"]}
anyhow.workspace = true
ureq.workspace = true
url.workspace = true
log.workspace = true

[lints]
workspace = true
