[package]
name = "generate"
version = "0.1.0"
edition = "2021"

[dependencies]
time = {version = "0.3.36", features = ["formatting"] }
zip = {version = "2.1.3", default-features = false, features = ["deflate"]}

[lib]

[features]
